### ISSUE TITLE
Pycord deprecated message.interaction

### ISSUE THREAD

**Issue by tibue99** [mahtoid/DiscordChatExporterPy#106]
### DiscordChatExporterPy Version

2.7.1

### Discord Version

Pycord 2.5.1.dev67+g19a9751d

### Bug Description

Pycord deprecated `message.interaction` in [this PR](https://github.com/Pycord-Development/pycord/pull/2409). This causes `build_interaction` to break. A temporary workaround would look like this:
```py
async def build_interaction(self):
    if not self.message.interaction:
        try:
            self.message.interaction = ""
        except AttributeError:
            self.message._interaction = ""
        return
```

### Bug Traceback

Traceback (most recent call last):
  File "C:\Users\Timo\Desktop\keks-bot\.venv\Lib\site-packages\chat_exporter\construct\transcript.py", line 171, in export
    return await super().build_transcript()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Timo\Desktop\keks-bot\.venv\Lib\site-packages\chat_exporter\construct\transcript.py", line 56, in build_transcript
    message_html, meta_data = await gather_messages(
                              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Timo\Desktop\keks-bot\.venv\Lib\site-packages\chat_exporter\construct\message.py", line 455, in gather_messages
    content_html, meta_data = await MessageConstruct(
                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Timo\Desktop\keks-bot\.venv\Lib\site-packages\chat_exporter\construct\message.py", line 92, in construct_message
    await self.build_message()
  File "C:\Users\Timo\Desktop\keks-bot\.venv\Lib\site-packages\chat_exporter\construct\message.py", line 98, in build_message
    await self.build_interaction()
  File "C:\Users\Timo\Desktop\keks-bot\.venv\Lib\site-packages\chat_exporter\construct\message.py", line 208, in build_interaction
    self.message.interaction = ""
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: property 'interaction' of 'Message' object has no setter

**Comment by mahtoid** [comment]
...why

**Comment by plun1331** [comment]
That was an unintended effect of making `interaction` a property so I could add a deprecation warning- that has been fixed
