### ISSUE TITLE
Export Error

### ISSUE THREAD

**Issue by xDragon11x13** [mahtoid/DiscordChatExporterPy#118]
### DiscordChatExporterPy Version

2.8.0

### Discord Version

2.4.0

### Bug Description

When I try to export a chat, I get this error. It says that I should please send it here

### ERROR CODE

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/chat_exporter/construct/transcript.py", line 187, in export
    return await super().build_transcript()
  File "/usr/local/lib/python3.9/dist-packages/chat_exporter/construct/transcript.py", line 59, in build_transcript
    message_html, meta_data = await gather_messages(
  File "/usr/local/lib/python3.9/dist-packages/chat_exporter/construct/message.py", line 484, in gather_messages
    content_html, meta_data = await MessageConstruct(
  File "/usr/local/lib/python3.9/dist-packages/chat_exporter/construct/message.py", line 100, in construct_message
    await self.build_message()
  File "/usr/local/lib/python3.9/dist-packages/chat_exporter/construct/message.py", line 109, in build_message
    await self.build_message_template()
  File "/usr/local/lib/python3.9/dist-packages/chat_exporter/construct/message.py", line 288, in build_message_template
    started = await self.generate_message_divider()
  File "/usr/local/lib/python3.9/dist-packages/chat_exporter/construct/message.py", line 346, in generate_message_divider
    ("USER_COLOUR", await self._gather_user_colour(self.message.author)),
  File "/usr/local/lib/python3.9/dist-packages/chat_exporter/construct/message.py", line 428, in _gather_user_colour
    member = await self._gather_member(author)
  File "/usr/local/lib/python3.9/dist-packages/chat_exporter/ext/cache.py", line 9, in func
    value = await coro
  File "/usr/local/lib/python3.9/dist-packages/chat_exporter/construct/message.py", line 417, in _gather_member
    member = self.guild.get_member(author.id)
AttributeError: 'NoneType' object has no attribute 'get_member'
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy
```

![image](https://github.com/user-attachments/assets/09c0a779-a516-4ff7-a4b1-cea81e86fdd9)

### MY CODE SNIPPED

```
            user_export = await user.create_dm()

            transcript = await chat_exporter.export(
                user_export,
                limit=None,
                tz_info="Europe/Berlin",
                military_time=True,
                bot=bot,
            )

            transcript_file = discord.File(
                io.BytesIO(transcript.encode()),
                filename=f"transcript-{user.name}.html",
            )

            await interaction.response.send_message(f"<:checkmark_ds:1177255274587885660> Chat erfolgreich exportiert.", ephemeral=True, file=transcript_file)
```

**Comment by mahtoid** [comment]
`DiscordChatExporterPy` isn't supported in DMs. 
If you'd like to export you own DMs then check out [DiscordChatExporter](https://github.com/Tyrrrz/DiscordChatExporter)
