### ISSUE TITLE
Hostname Error

### ISSUE THREAD

**Issue by iDaFox** [mahtoid/DiscordChatExporterPy#12]
![image](https://user-images.githubusercontent.com/46523983/126524210-b0bb40f7-911d-4b66-b2da-05a64fe33559.png)
Traceback (most recent call last):
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\site-packages\chat_exporter\chat_exporter.py", line 36, in export
    return (await Transcript.export(channel, limit, set_timezone)).html
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\site-packages\chat_exporter\chat_exporter.py", line 105, in export
    timezone_string=timezone(timezone_string))\
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\site-packages\chat_exporter\chat_exporter.py", line 123, in build_transcript
    message_html += await Message(m, previous_message, self.timezone_string).build_message()
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\site-packages\chat_exporter\chat_exporter.py", line 179, in build_message
    await self.build_content()
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\site-packages\chat_exporter\chat_exporter.py", line 241, in build_content
    ("EDIT", self.time_string_edit, PARSE_MODE_NONE)
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\site-packages\chat_exporter\build_html.py", line 27, in fill_out
    v = ParseMarkdown(v).standard_message_flow()
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\site-packages\chat_exporter\parse_markdown.py", line 13, in standard_message_flow
    self.parse_emoji()
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\site-packages\chat_exporter\parse_markdown.py", line 59, in parse_emoji
    self.content = convert_emoji([word for word in self.content])
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\site-packages\chat_exporter\emoji_convert.py", line 111, in convert_emoji
    return "".join(convert(ch) for ch in graphemes(string))
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\site-packages\chat_exporter\emoji_convert.py", line 111, in <genexpr>
    return "".join(convert(ch) for ch in graphemes(string))
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\site-packages\chat_exporter\emoji_convert.py", line 95, in convert
    if valid_src(src):
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\site-packages\chat_exporter\emoji_convert.py", line 47, in valid_src
    req = requests.head(src)
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 104, in head
    return request('head', url, **kwargs)
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 506, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Users\yilma\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 807, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy

**Comment by iDaFox** [comment]
I found the problem, bot doesnt get transcript if there are emoji in chat.

**Comment by iDaFox** [comment]
I was using old request module, so its solved with "pip install --upgrade requests" command. Thanks to **mahtoid**.
