### ISSUE TITLE
Embeds(?) stopping exporting

### ISSUE THREAD

**Issue by Cuts-xo** [mahtoid/DiscordChatExporterPy#17]
```
Traceback (most recent call last):
  File "C:\Users\Waili\AppData\Local\Programs\Python\Python38\lib\site-packages\chat_exporter\chat_exporter.py", line 61, in quick_export     
    transcript = await Transcript.export(ctx.channel, None, "Europe/London")
  File "C:\Users\Waili\AppData\Local\Programs\Python\Python38\lib\site-packages\chat_exporter\chat_exporter.py", line 115, in export
    transcript = await Transcript(
  File "C:\Users\Waili\AppData\Local\Programs\Python\Python38\lib\site-packages\chat_exporter\chat_exporter.py", line 147, in build_transcript
    message_html += await Message(m, previous_message, self.timezone_string).build_message()
  File "C:\Users\Waili\AppData\Local\Programs\Python\Python38\lib\site-packages\chat_exporter\chat_exporter.py", line 213, in build_message   
    await self.build_reference()
  File "C:\Users\Waili\AppData\Local\Programs\Python\Python38\lib\site-packages\chat_exporter\chat_exporter.py", line 315, in build_reference 
    if not self.message.reference:
AttributeError: 'Message' object has no attribute 'reference'
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy
```

The error i get.

**Comment by mahtoid** [comment]
This was solved in Discord. 
Remember to update your modules! 

💜
