### ISSUE TITLE
what is this

### ISSUE THREAD

**Issue by KommandNyang** [mahtoid/DiscordChatExporterPy#25]
Traceback (most recent call last):
  File "C:\Users\user\Documents\GitHub\p-pg-ticketbot\main.py", line 2, in <module>
    from discord.ext import commands
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\__init__.py", line 25, in <module>
    from .client import Client
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 53, in <module>
    from .webhook import Webhook
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\webhook\__init__.py", line 12, in <module>
    from .async_ import *
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\webhook\async_.py", line 49, in <module>
    from ..channel import PartialMessageable
ImportError: cannot import name 'PartialMessageable' from 'discord.channel' (C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\channel.py)

**Comment by KommandNyang** [comment]
> Could you give me a little information on what discordpy fork you're using, please?
> 
> I did have a ~similar issue like this before while testing with `enhanced-dpy`. The solution was to fetch the channel (and guild).
> 
> This issue is irrelevant from `DiscordChatExporterPy` though.

I'll just give you all of software's info that can related with this

Python 3.8.5 (uses 3.9.7 too but 3.8.5 main)
Microsoft Windows 11 Home Build 22523.1000
(Discord.py) Py-cord  2.0.0a4748+gc602bc45
aiohttp  3.7.4.post0

**Comment by KommandNyang** [comment]
> Could you give me a little information on what discordpy fork you're using, please?
> 
> I did have a ~similar issue like this before while testing with `enhanced-dpy`. The solution was to fetch the channel (and guild).
> 
> This issue is irrelevant from `DiscordChatExporterPy` though.

sorry 
umm.. i tried to update python to 39
and it perfectly works

**Comment by mahtoid** [comment]
Quite a weird solve, I'm assuming `pycord` now requires Python 3.9 for some usage. Either way, I'm glad you got it sorted!
