### ISSUE TITLE
error exporting

### ISSUE THREAD

**Issue by lktoby** [mahtoid/DiscordChatExporterPy#26]
[this is the fork i'm using](https://github.com/iDevision/enhanced-discord.py/tree/2.0)
the bot is running on python 3.9
when i attempted to create logs of a channel it gave me this error:
```Traceback (most recent call last):
  File "/home/toby/.local/lib/python3.9/site-packages/chat_exporter/chat_exporter.py", line 39, in export
    return (await Transcript.export(channel, limit, set_timezone)).html
  File "/home/toby/.local/lib/python3.9/site-packages/chat_exporter/chat_exporter.py", line 110, in export
    messages = await channel.history(limit=limit).flatten()
  File "/home/toby/.local/lib/python3.9/site-packages/discord/iterators.py", line 120, in flatten
    return [element async for element in self]
  File "/home/toby/.local/lib/python3.9/site-packages/discord/iterators.py", line 120, in <listcomp>
    return [element async for element in self]
  File "/home/toby/.local/lib/python3.9/site-packages/discord/iterators.py", line 124, in __anext__
    return await self.next()
  File "/home/toby/.local/lib/python3.9/site-packages/discord/iterators.py", line 323, in next
    await self.fill_messages()
  File "/home/toby/.local/lib/python3.9/site-packages/discord/iterators.py", line 345, in fill_messages
    if self._get_retrieve():
  File "/home/toby/.local/lib/python3.9/site-packages/discord/iterators.py", line 332, in _get_retrieve
    if l is None or l > 100:
TypeError: '>' not supported between instances of 'Guild' and 'int'
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy
```

**Comment by mahtoid** [comment]
You are putting the arguments in the parameters in an incorrect order. 
The correct order is `channel`, `guild`, `limit` and `set_timezone`. 

I'd recommend using keyword arguments when passing in variables.
For example: `transcript = await chat_exporter.export(channel=ctx.channel, guild=ctx.guild, limit=1000, set_timezone="UTC")`

The only required argument is `channel`, the rest are optional and can be added when and as you need/want them.
_Please note, I'm pretty sure it is still needed to send `guild` while using edpy_

**Comment by mahtoid** [comment]
Let me know if you still have any issues 😄

**Comment by lktoby** [comment]
remove the `guild` parameter and now it's working, thank you so much!
