### ISSUE TITLE
I have this error. How do I solve it?

### ISSUE THREAD

**Issue by MrPotatuh** [mahtoid/DiscordChatExporterPy#30]
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/chat_exporter/construct/transcript.py", line 59, in export
    return await super().build_transcript()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/chat_exporter/construct/transcript.py", line 32, in build_transcript
    message_html = await Message(self.messages, self.channel.guild, self.pytz_timezone).gather()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/chat_exporter/construct/message.py", line 281, in gather
    message_html += await MessageConstruct(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/chat_exporter/construct/message.py", line 67, in construct_message
    await self.build_message()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/chat_exporter/construct/message.py", line 74, in build_message
    await self.build_assets()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/chat_exporter/construct/message.py", line 162, in build_assets
    for c in self.message.components:
AttributeError: 'Message' object has no attribute 'components'
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy
Command raised an exception: AttributeError: 'NoneType' object has no attribute 'html'

**Comment by Hichoow** [comment]
Downgrade to version 1.7.3

pip install chat-exporter==1.7.3

**Comment by mahtoid** [comment]
As @Hichoow has mentioned, for this issue you need to downgrade to `chat-exporter 1.7.3` using `pip install chat-exporter==1.7.3`
