### ISSUE TITLE
I'm having issues lately with the library (since I havent used it in a month or 2) and get these errors:

### ISSUE THREAD

**Issue by Bertie2006** [mahtoid/DiscordChatExporterPy#32]
Traceback (most recent call last):
  File "C:\Users\bert\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ui\view.py", line 368, in _scheduled_task
    await item.callback(interaction)
  File "c:\Users\bert\Downloads\joscheats ticket bot.py", line 130, in Save_transcript_button
    transcript = await chat_exporter.export(channel)
  File "C:\Users\bert\AppData\Local\Programs\Python\Python38\lib\site-packages\chat_exporter\chat_exporter.py", line 48, in export
    return (
AttributeError: 'NoneType' object has no attribute 'html'
I re-pip-installed the library to make sure I got the newest version, on 2.1 now and i get this error...
also set_timezone isnt recognized anymore?

**Comment by Bertie2006** [comment]
when I downgrade to 1.7.3, I get this error: Traceback (most recent call last):
  File "C:\Users\bert\AppData\Local\Programs\Python\Python38\lib\site-packages\chat_exporter\chat_exporter.py", line 44, in export
    return (await Transcript.export(channel, limit, set_timezone)).html
  File "C:\Users\bert\AppData\Local\Programs\Python\Python38\lib\site-packages\chat_exporter\chat_exporter.py", line 127, in export
    messages = await channel.history(limit=limit, oldest_first=True).flatten()
AttributeError: 'async_generator' object has no attribute 'flatten'
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy
Ignoring exception in view <final timeout=None children=3> for item <Button style=<ButtonStyle.primary: 1> url=None disabled=False label='📄Save transcript' emoji=None row=None>:
Traceback (most recent call last):
  File "C:\Users\bert\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ui\view.py", line 368, in _scheduled_task
    await item.callback(interaction)
  File "c:\Users\bert\Downloads\joscheats ticket bot.py", line 131, in Save_transcript_button
    transcript_file = discord.File(io.BytesIO(transcript.encode()),filename=f"{channel.name}.html")
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by mahtoid** [comment]
Hello @Bertie2006 - sorry for the delay.

I cannot tell much from the first traceback you gave me, however the second traceback is because you are using `discord.py=2.0.0a` and require the patch which is in `chat-exporter==2.1`.

If you could upgrade again to `2.1` using `pip install --upgrade chat-exporter` then if you run in to the issue again, give me the full traceback.

**Comment by Bertie2006** [comment]
I managed to fix the library myself. In the file to make embeds, in dpy 2.0 discord.Embed.Empty doesn't exist. It is None now.

**Comment by Bertie2006** [comment]
They also changed the chat history.flatten(), it's something else now.

**Comment by mahtoid** [comment]
I'm glad you got it fixed! Sorry for the delay.

The `.flatten()` issue is solved in `chat-exporter` 2.1
The `discord.Embed.Empty` I have the solve locally, which I'll push to the repo in ~10-15 minutes, then to `pypi` probably tomorrow.

If you have any other issues or want to report any bugs; then feel free to re-open the issue, create another one or alternatively join the Discord where I respond much faster: discord.gg/mq3hYaJSfa

Thank you, and sorry once again for the delay! 💜
