### ISSUE TITLE
Error on save

### ISSUE THREAD

**Issue by ZeusHay** [mahtoid/DiscordChatExporterPy#35]
> Traceback (most recent call last):
  File "C:\Users\Developer\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\transcript.py", line 67, in export
    return await super().build_transcript()
  File "C:\Users\Developer\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\transcript.py", line 37, in build_transcript
    message_html = await Message(self.messages, self.channel.guild, self.pytz_timezone).gather()
  File "C:\Users\Developer\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\message.py", line 281, in gather
    message_html += await MessageConstruct(
  File "C:\Users\Developer\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\message.py", line 57, in __init__
    self.message_created_at, self.message_edited_at = self.set_time()
  File "C:\Users\Developer\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\message.py", line 252, in set_time
    created_at_str = self.to_local_time_str(message.created_at)
  File "C:\Users\Developer\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\message.py", line 261, in to_local_time_str
    local_time = time.astimezone(timezone(self.pytz_timezone))
  File "C:\Users\Developer\AppData\Local\Programs\Python\Python39\lib\site-packages\pytz\__init__.py", line 170, in timezone
    if zone.upper() == 'UTC':
AttributeError: 'int' object has no attribute 'upper'
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy

**Comment by mahtoid** [comment]
I have a feeling you are using the wrong argument placement, when adding additional arguments in to `chat_exporter` function you are using, please use keyword arguments.

For 2.0+:
```
    transcript = await chat_exporter.export(
        ctx.channel,
        limit=limit,
        tz_info=tz_info,
        bot=bot,
    )
```

For 1.7.3:
```
    transcript = await chat_exporter.export(
        ctx.channel,
        limit=limit,
        set_timezone=tz_info,
    )
```

Respectively, the `limit` would be an integer value which will limit the amount of messages to capture in the history. The `tz_info` or `set_timezone` would be a [TZ database name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

If you have any more problems feel free to re-open the ticket.
