### ISSUE TITLE
Error attribute 'components'

### ISSUE THREAD

**Issue by ZeusHay** [mahtoid/DiscordChatExporterPy#36]
> Traceback (most recent call last):
  File "C:\Users\Developer\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\transcript.py", line 67, in export
    return await super().build_transcript()
  File "C:\Users\Developer\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\transcript.py", line 37, in build_transcript
    message_html = await Message(self.messages, self.channel.guild, self.pytz_timezone).gather()
  File "C:\Users\Developer\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\message.py", line 281, in gather
    message_html += await MessageConstruct(
  File "C:\Users\Developer\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\message.py", line 67, in construct_message  
    await self.build_message()
  File "C:\Users\Developer\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\message.py", line 74, in build_message      
    await self.build_assets()
  File "C:\Users\Developer\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\message.py", line 162, in build_assets
    for c in self.message.components:
AttributeError: 'Message' object has no attribute 'components'
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy

**Comment by mahtoid** [comment]
Hello @ZeusHay - sorry for the delay.

You are receiving this issue because you are using `discord.py 1.7.3` (or fork equivalent to that version). As suggested in the README, when you are using this version - please use `chat-exporter 1.7.3`

You can downgrade with the following command: `pip install chat-exporter==1.7.3`

Feel free to re-open this ticket if you have any further issues.
