### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'html'

### ISSUE THREAD

**Issue by XSlizeMoon** [mahtoid/DiscordChatExporterPy#39]
So, I am trying to use quick_export, however, I am getting a NoneType issue.
# Error
```py
14.04 21:05:49 [Bot] Traceback (most recent call last):
14.04 21:05:49 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/construct/transcript.py", line 67, in export
14.04 21:05:49 [Bot] return await super().build_transcript()
14.04 21:05:49 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/construct/transcript.py", line 37, in build_transcript
14.04 21:05:49 [Bot] message_html = await Message(self.messages, self.channel.guild, self.pytz_timezone).gather()
14.04 21:05:49 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/construct/message.py", line 281, in gather
14.04 21:05:49 [Bot] message_html += await MessageConstruct(
14.04 21:05:49 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/construct/message.py", line 67, in construct_message
14.04 21:05:49 [Bot] await self.build_message()
14.04 21:05:49 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/construct/message.py", line 74, in build_message
14.04 21:05:49 [Bot] await self.build_assets()
14.04 21:05:49 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/construct/message.py", line 162, in build_assets
14.04 21:05:49 [Bot] for c in self.message.components:
14.04 21:05:49 [Bot] AttributeError: 'Message' object has no attribute 'components'
14.04 21:05:49 [Bot] Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy
14.04 21:05:49 [Bot] Ignoring exception in on_button_click
14.04 21:05:49 [Bot] Traceback (most recent call last):
14.04 21:05:49 [Bot] File "/.local/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
14.04 21:05:49 [Bot] await coro(*args, **kwargs)
14.04 21:05:49 [Bot] File "/hbot/events/buttons.py", line 227, in on_button_click
14.04 21:05:49 [Bot] transcript = await chat_exporter.quick_export(interaction.channel)
14.04 21:05:49 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/chat_exporter.py", line 16, in quick_export
14.04 21:05:49 [Bot] transcript = (
14.04 21:05:52 [Bot] AttributeError: 'NoneType' object has no attribute 'html'
```

# Code:

```py
elif interaction.component.custom_id == ("archyes"):
        channel = await self.bot.fetch_channel('953298647473328178')
        embedVar=discord.Embed(title = interaction.channel.name, description = f'{interaction.user.mention} has archived ``#{interaction.channel.name}``', color = 14177041)
        embedVar.timestamp = datetime.datetime.utcnow()
        embedVar.set_footer(text='\u200b')
        await interaction.channel.purge(limit=1, check=None, before=None)
        transcript = await chat_exporter.quick_export(interaction.channel)
        transcript_file = discord.File(io.BytesIO(transcript.encode()), filename=f"{interaction.channel.name}.html")
        await channel.send(file=transcript_file, embed = embedVar)
        await interaction.channel.delete()
```

**Comment by mahtoid** [comment]
Hello @XSlizeMoon, 

As mentioned in the README, when using `discord.py==1.7.3` (or fork equivalent) you will need to use `chat-exporter==1.7.3`. 

You can downgrade by using: `pip install chat-exporter==1.7.3`.

If for some reason that does not solve your issue, please re-open the issue or create a new one with the issue you are facing.

**Note**
According to [Danny's Gist](https://gist.github.com/Rapptz/c4324f17a80c94776832430007ad40e6) upon return, `discord.py==1.7.3` will cease from working due to `discord` decommissioning API v6 and v7 (1.7.3 uses v7) on May 1st. You may wish to look to upgrade.
