### ISSUE TITLE
AttributeError: 'Member' object has no attribute 'display_avatar'

### ISSUE THREAD

**Issue by Owned67** [mahtoid/DiscordChatExporterPy#40]
`Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\chat_exporter\chat_exporter.py", line 44, in export
    return (await Transcript.export(channel, limit, set_timezone)).html
  File "C:\Python39\lib\site-packages\chat_exporter\chat_exporter.py", line 129, in export
    transcript = await Transcript(
  File "C:\Python39\lib\site-packages\chat_exporter\chat_exporter.py", line 161, in build_transcript
    message_html += await Message(m, previous_message, self.timezone_string).build_input()
  File "C:\Python39\lib\site-packages\chat_exporter\chat_exporter.py", line 237, in build_input
    await self.build_message()
  File "C:\Python39\lib\site-packages\chat_exporter\chat_exporter.py", line 253, in build_message
    await self.build_message_template()
  File "C:\Python39\lib\site-packages\chat_exporter\chat_exporter.py", line 298, in build_message_template
    await self.generate_message_divider()
  File "C:\Python39\lib\site-packages\chat_exporter\chat_exporter.py", line 333, in generate_message_divider
    avatar_url = str(self.message.author.display_avatar)
AttributeError: 'Member' object has no attribute 'display_avatar'
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy
Failed to send ticket transcript to ticket creator. (ticket-9)
Ignoring exception in on_button_click
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\discord\client.py", line 308, in _run_event
    await coro(*args, **kwargs)
  File "F:\ticketbot\modules\tickets.py", line 37, in on_button_click
    await self.closeTicket(channel, False)
  File "F:\ticketbot\modules\tickets.py", line 121, in closeTicket
    await self.createTranscript(ticket_id, channel)
  File "F:\ticketbot\modules\tickets.py", line 135, in createTranscript
    await ticketLogChannel.send(file=discord.File(io.BytesIO(transcript.encode()), filename=f"{channel.name}.html"))
AttributeError: 'NoneType' object has no attribute 'encode`

python 3.9
chat-exporter 1.7.3 (2.1 don't work)
discord 2.0.0a

**Comment by mahtoid** [comment]
Hello @Owned67 

The `AttributeError: 'Member' object has no attribute 'display_avatar'` is one of the changes which took place in `discord.py==2.0.0a`. You would need to use `chat-exporter==2.1.1` onwards.

Could you upgrade again with `pip install --upgrade chat-exporter` and let me know which issue you have with the latest version, and we'll work to solve that.

**Comment by Owned67** [comment]
I've solved it with install a new instance of discord.py => 1.7.3

Thanks
