### ISSUE TITLE
I get this error whenever i use the command 

### ISSUE THREAD

**Issue by sh0e** [mahtoid/DiscordChatExporterPy#5]
Error during transcript generation!
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/chat_exporter/chat_exporter.py", line 55, in quick_export
    transcript = await Transcript.export(ctx.channel, None, "Europe/London")
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/chat_exporter/chat_exporter.py", line 100, in export
    transcript = await Transcript(channel=channel, guild=channel.guild, messages=messages,
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/chat_exporter/chat_exporter.py", line 119, in build_transcript
    message_html += await Message(m, previous_message, self.timezone_string).build_message()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/chat_exporter/chat_exporter.py", line 175, in build_message
    await self.build_reference()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/chat_exporter/chat_exporter.py", line 244, in build_reference
    message: discord.Message = await self.message.channel.fetch_message(self.message.reference.message_id)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/abc.py", line 970, in fetch_message
    data = await self._state.http.get_message(channel.id, id)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/http.py", line 241, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 20002): Only bots can use this endpoint

**Comment by mahtoid** [comment]
Hello, sorry for the late response.

Are you trying to run the module via a bot token?

**Comment by mahtoid** [comment]
Closing the ticket, due to no response. 

Feel free to join the Discord or re-open a ticket if you're still facing the issue.
