### ISSUE TITLE
I can't create a new transcript

### ISSUE THREAD

**Issue by berchbrown** [mahtoid/DiscordChatExporterPy#51]
### DiscordChatExporterPy Version

2.2.1

### Discord Version

1.7.2

### Bug Description

When i wanted to create a new transcript, it shows me this error:

### Bug Traceback

```
Traceback (most recent call last):
  File "C:\Python\fantasupport\venv\lib\site-packages\chat_exporter\construct\transcript.py", line 74, in export
    return await super().build_transcript()
  File "C:\Python\fantasupport\venv\lib\site-packages\chat_exporter\construct\transcript.py", line 39, in build_transcript
    message_html = await Message(
  File "C:\Python\fantasupport\venv\lib\site-packages\chat_exporter\construct\message.py", line 302, in gather
    message_html += await MessageConstruct(
  File "C:\Python\fantasupport\venv\lib\site-packages\chat_exporter\construct\message.py", line 69, in construct_message
    await self.build_message()
  File "C:\Python\fantasupport\venv\lib\site-packages\chat_exporter\construct\message.py", line 76, in build_message
    await self.build_assets()
  File "C:\Python\fantasupport\venv\lib\site-packages\chat_exporter\construct\message.py", line 163, in build_assets
    for c in self.message.components:
AttributeError: 'Message' object has no attribute 'components'
Ignoring exception in command save:
Traceback (most recent call last):
  File "C:\Python\fantasupport\venv\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Python\fantasupport\test.py", line 16, in save
    await chat_exporter.export(ctx)
  File "C:\Python\fantasupport\venv\lib\site-packages\chat_exporter\chat_exporter.py", line 50, in export
    return (
AttributeError: 'NoneType' object has no attribute 'html'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python\fantasupport\venv\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Python\fantasupport\venv\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Python\fantasupport\venv\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'html'
```

**Comment by mahtoid** [comment]
For usage of `discord.py 1.7.3` (or before) you have to use `chat-exporter 1.7.3`
To downgrade, run: `pip install chat-exporter==1.7.3`
