### ISSUE TITLE
TypeError: demojize() got an unexpected keyword argument 'use_aliases'

### ISSUE THREAD

**Issue by Amxgh** [mahtoid/DiscordChatExporterPy#52]
### DiscordChatExporterPy Version

2.2.1

### Discord Version

0.0.1

### Bug Description

I have a command that sends the transcript of a channel when that channel is deleted. When I tried to delete a channel, it errored.

cogs.tickets
```python
    @bridge.bridge_command(aliases=["del"])
    @commands.has_role("Staff")
    async def delete(self, ctx):
        """Delete a ticket!"""
        res = await General.delete(ctx)
        if res:
            await ctx.respond(res)
```

general.py
```python
   async def delete(ctx):
        embed = discord.Embed(title="This ticket will be deleted in 10 seconds!", color=neg_color)
        if ("MILESTONES" == ctx.channel.category.name) or not ctx.channel.category or ctx.channel.category.name not in ticket_categories.values():
            return "This command cannot be used here"
        if ctx.channel.category.name == ticket_categories["registrees"]:
            member = await get_ticket_creator(ctx.channel)
            if member:
                ign, uuid = await get_mojang_profile(await name_grabber(member))
                await Union(user=member).sync(ctx, ign, None, True)
                embed.set_footer(text=f"{ign}'s roles have been updated automatically!")

        # Send deletion warning and gather transcript
        await ctx.respond(embed=embed)
        transcript = await create_transcript(ctx.channel)

        # Sleep and delete channel
        await asyncio.sleep(10)
        await discord.TextChannel.delete(ctx.channel)

        if transcript:
            # Log outcome
            await log_event(f"{ctx.channel.name} was deleted by {ctx.author}")
            await (await bot.fetch_user(ctx.channel.topic.split("|")[0])).send(embed=ticket_deleted_embed.set_footer(text=ctx.channel.name), file=transcript)
            await bot.get_channel(log_channel_id).send(file=transcript)
```

### Bug Traceback

Traceback (most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/chat_exporter/construct/transcript.py", line 74, in export
    return await super().build_transcript()
  File "/home/container/.local/lib/python3.9/site-packages/chat_exporter/construct/transcript.py", line 39, in build_transcript
    message_html = await Message(
  File "/home/container/.local/lib/python3.9/site-packages/chat_exporter/construct/message.py", line 302, in gather
    message_html += await MessageConstruct(
  File "/home/container/.local/lib/python3.9/site-packages/chat_exporter/construct/message.py", line 69, in construct_message
    await self.build_message()
  File "/home/container/.local/lib/python3.9/site-packages/chat_exporter/construct/message.py", line 76, in build_message
    await self.build_assets()
  File "/home/container/.local/lib/python3.9/site-packages/chat_exporter/construct/message.py", line 164, in build_assets
    self.components += await Component(c, self.guild).flow()
  File "/home/container/.local/lib/python3.9/site-packages/chat_exporter/construct/assets/component.py", line 100, in flow
    await self.build_component(c)
  File "/home/container/.local/lib/python3.9/site-packages/chat_exporter/construct/assets/component.py", line 43, in build_component
    await self.build_menu(c)
  File "/home/container/.local/lib/python3.9/site-packages/chat_exporter/construct/assets/component.py", line 68, in build_menu
    content = await self.build_menu_options(options)
  File "/home/container/.local/lib/python3.9/site-packages/chat_exporter/construct/assets/component.py", line 82, in build_menu_options
    content.append(await fill_out(self.guild, component_menu_options_emoji, [
  File "/home/container/.local/lib/python3.9/site-packages/chat_exporter/ext/html_generator.py", line 36, in fill_out
    v = await ParseMarkdown(v).special_emoji_flow()
  File "/home/container/.local/lib/python3.9/site-packages/chat_exporter/parse/markdown.py", line 48, in special_emoji_flow
    await self.parse_emoji()
  File "/home/container/.local/lib/python3.9/site-packages/chat_exporter/parse/markdown.py", line 62, in parse_emoji
    self.content = await convert_emoji([word for word in self.content])
  File "/home/container/.local/lib/python3.9/site-packages/chat_exporter/ext/emoji_convert.py", line 88, in convert_emoji
    x.append(await convert(ch))
  File "/home/container/.local/lib/python3.9/site-packages/chat_exporter/ext/emoji_convert.py", line 74, in convert
    shortcode = emoji.demojize(char, use_aliases=True)
TypeError: demojize() got an unexpected keyword argument 'use_aliases'

**Comment by mahtoid** [comment]
Update your version of `chat-exporter`, this was hotfixed for `2.2.2`

To upgrade, run: `pip install --upgrade chat-exporter`
