### ISSUE TITLE
AttributeError: 'Message' object has no attribute 'components'

### ISSUE THREAD

**Issue by Joniii11** [mahtoid/DiscordChatExporterPy#56]
### DiscordChatExporterPy Version

2.2.2

### Discord Version

1.7.3

### Bug Description

I tried to archive that but instead of that it is archiving the channel it spits 2 errors out, tried like the documentation did and copyied that and if u try to execute that command, it will come that error out AttributeError: 'Message' object has no attribute 'components'

### Bug Traceback
```
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\chat_exporter\construct\transcript.py", line 74, in export
    return await super().build_transcript()
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\chat_exporter\construct\transcript.py", line 39, in build_transcript
    message_html = await Message(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\chat_exporter\construct\message.py", line 302, in gather    
    message_html += await MessageConstruct(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\chat_exporter\construct\message.py", line 69, in construct_message
    await self.build_message()
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\chat_exporter\construct\message.py", line 76, in build_message
    await self.build_assets()
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\chat_exporter\construct\message.py", line 163, in build_assets
    for c in self.message.components:
AttributeError: 'Message' object has no attribute 'components'
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy
```
### Additional Information

And this is the code i used:
```py
@client.command()
@commands.has_role(MANAGEMENT_ROLE_ID)
async def archive(ctx: commands.Context): 
    transcript = await chat_exporter.export(
        ctx.channel,
        tz_info="UTC",
        military_time=True, 
        bot=client
        )
    if transcript is None:
        return

    transcript_file = discord.File(
        io.BytesIO(transcript.encode()),
        filename=f"transcript-{ctx.channel.name}",
    )
    await ctx.send(file=transcript_file)
```

**Comment by mahtoid** [comment]
Downgrade to `chat-exporter==1.7.3`. 
You can do this by using: `pip install chat-exporter==1.7.3`

`chat-exporter==2.0` and above is for dpy 2.0  (or fork equivalent)
