### ISSUE TITLE
Timzeone not working

### ISSUE THREAD

**Issue by CodeInFilth** [mahtoid/DiscordChatExporterPy#58]
### DiscordChatExporterPy Version

Latest

### Discord Version

Latest

### Bug Description

I am attempting to change the timzeone from UTC over to PST.

According to your docs I notice that it should work by adding to the kwargs like so:

`await chat_exporter.export(ctx.channel, limit=1, tz_info="PST")`

fails and produces this:
```python
Traceback (most recent call last):
  File "/home/auroratrades/public_python/chatExport/DiscordChatExporterPy/chat_exporter/construct/transcript.py", line 74, in export
    return await super().build_transcript()
  File "/home/auroratrades/public_python/chatExport/DiscordChatExporterPy/chat_exporter/construct/transcript.py", line 39, in build_transcript
    message_html = await Message(
  File "/home/auroratrades/public_python/chatExport/DiscordChatExporterPy/chat_exporter/construct/message.py", line 302, in gather
    message_html += await MessageConstruct(
  File "/home/auroratrades/public_python/chatExport/DiscordChatExporterPy/chat_exporter/construct/message.py", line 59, in __init__
    self.message_created_at, self.message_edited_at = self.set_time()
  File "/home/auroratrades/public_python/chatExport/DiscordChatExporterPy/chat_exporter/construct/message.py", line 267, in set_time
    created_at_str = self.to_local_time_str(message.created_at)
  File "/home/auroratrades/public_python/chatExport/DiscordChatExporterPy/chat_exporter/construct/message.py", line 276, in to_local_time_str
    local_time = time.astimezone(timezone(self.pytz_timezone))
  File "/usr/local/lib/python3.8/site-packages/pytz/__init__.py", line 188, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: 'PST'
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy
2022-08-18 20:12:12 ERROR    discord.client Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "main2.py", line 35, in on_message
    transcript = await chat_exporter.export(ctx.channel, limit=1, tz_info="PST")
  File "/home/auroratrades/public_python/chatExport/DiscordChatExporterPy/chat_exporter/chat_exporter.py", line 50, in export
    return (
AttributeError: 'NoneType' object has no attribute 'html'
```

this fails, even changing the UTC over to PST in the chat_exporter.py for a 'hardcoded' fix seems to produce the same error.

For now while this seems to be broken I will just be hiding the dates and times in the exported chat. is a shame tho

**Comment by mahtoid** [comment]
Only TZ Database Names are accepted. 
Checkout: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
Everything under the `TZ Database Name` will work
