### ISSUE TITLE
Basic example errors

### ISSUE THREAD

**Issue by Noah-Wilderom** [mahtoid/DiscordChatExporterPy#59]
### DiscordChatExporterPy Version

2.2.2

### Discord Version

2.0.0

### Bug Description

Used the example in the README 
```Python
channel = ctx.channel
archive_channel = ctx.guild.get_channel(1006895272565166130)

    if channel and archive_channel:
       transcript = await chat_exporter.export(channel=channel)
       transcript_file = discord.File(io.BytesIO(transcript.encode()),
                                       filename=f"{channel.name}.html")

       await archive_channel.send(file=transcript_file)
```

For the first error there was a embed in the channel that had no color (default) after giving the embed a color and trying again gave me the 2nd error.

The only message that is in the channel is 1 embed with only no title

### Bug Traceback

```Logs
Traceback (most recent call last):
  File "C:\Users\wilde\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\transcript.py", line 74, in export
    return await super().build_transcript()
  File "C:\Users\wilde\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\transcript.py", line 39, in build_transcript
    message_html = await Message(
  File "C:\Users\wilde\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\message.py", line 302, in gather
    message_html += await MessageConstruct(
  File "C:\Users\wilde\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\message.py", line 69, in construct_message
    await self.build_message()
  File "C:\Users\wilde\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\message.py", line 76, in build_message
    await self.build_assets()
  File "C:\Users\wilde\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\message.py", line 158, in build_assets
    self.embeds += await Embed(e, self.guild).flow()
  File "C:\Users\wilde\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\assets\embed.py", line 49, in flow
  File "C:\Users\wilde\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\assets\embed.py", line 63, in build_colour
    (self.embed.colour.r, self.embed.colour.g, self.embed.colour.b)
AttributeError: 'NoneType' object has no attribute 'r'
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy
```

```Logs
Traceback (most recent call last):
  File "C:\Users\wilde\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\transcript.py", line 74, in export
    return await super().build_transcript()
  File "C:\Users\wilde\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\transcript.py", line 39, in build_transcript
    message_html = await Message(
  File "C:\Users\wilde\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\message.py", line 302, in gather
    message_html += await MessageConstruct(
  File "C:\Users\wilde\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\message.py", line 69, in construct_message
    await self.build_message()
  File "C:\Users\wilde\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\message.py", line 76, in build_message
    await self.build_assets()
  File "C:\Users\wilde\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\message.py", line 158, in build_assets
    self.embeds += await Embed(e, self.guild).flow()
  File "C:\Users\wilde\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\assets\embed.py", line 57, in flow
    await self.build_embed()
  File "C:\Users\wilde\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\assets\embed.py", line 145, in build_embed
    self.embed = await fill_out(self.guild, embed_body, [
  File "C:\Users\wilde\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\ext\html_generator.py", line 38, in fill_out
    base = base.replace("{{" + k + "}}", v)
TypeError: replace() argument 2 must be str, not None
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy
```

**Comment by Noah-Wilderom** [comment]
After giving the embed a title seems to have solved it, this does mean you need to have a full embed or it would not work.

**Comment by mahtoid** [comment]
It looks like `discord.py` changed something on their release of `2.0`.

I'll add this to the list of things to do, thank you for bringing it to my attention.

**Comment by mahtoid** [comment]
Closing due to inactivity, feel free to re-open if you have anything.
