### ISSUE TITLE
Error when exporting channel with references

### ISSUE THREAD

**Issue by debnet** [mahtoid/DiscordChatExporterPy#6]
```python_traceback
Traceback (most recent call last):
  File "/var/roothome/fallout/fallout/lib64/python3.9/site-packages/chat_exporter/chat_exporter.py", line 46, in raw_export
    return (await Transcript.raw_export(channel, messages, set_timezone)).html
  File "/var/roothome/fallout/fallout/lib64/python3.9/site-packages/chat_exporter/chat_exporter.py", line 109, in raw_export
    transcript = await Transcript(channel=channel, guild=channel.guild, messages=messages,
  File "/var/roothome/fallout/fallout/lib64/python3.9/site-packages/chat_exporter/chat_exporter.py", line 119, in build_transcript
    message_html += await Message(m, previous_message, self.timezone_string).build_message()
  File "/var/roothome/fallout/fallout/lib64/python3.9/site-packages/chat_exporter/chat_exporter.py", line 189, in build_message
    await self.generate_message_divider()
  File "/var/roothome/fallout/fallout/lib64/python3.9/site-packages/chat_exporter/chat_exporter.py", line 213, in generate_message_divider
    self.message_html += await fill_out(self.message.guild, start_message, [
  File "/var/roothome/fallout/fallout/lib64/python3.9/site-packages/chat_exporter/build_html.py", line 36, in fill_out
    base = base.replace("{{" + k + "}}", v)
TypeError: replace() argument 2 must be str, not MessageReference
```

Code:

```python
            deleted_messages = await new_channel.purge()
            if deleted_messages:
                transcript = await chat_exporter.raw_export(new_channel, deleted_messages, 'Europe/Paris')
                if transcript:
                    for member in new_channel.members:
                        if member.bot:
                            continue
                        file = File(io.BytesIO(transcript.encode()), filename=f'{new_channel.name}.html')
                        await member.send(file=file)
```

**Comment by mahtoid** [comment]
Thank you for your report, this has now been fixed - please update your module or pull the latest files to your repository.

Closing out this ticket, if you find any more problems, please do let me know! 💜 

NOTE: Since you're purging the messages, then exporting - references will come up as they have been deleted (I may investigate this to see if there is anything that could be done to make this smarter, but I may be limited by Discord).
