### ISSUE TITLE
Transcript not generating

### ISSUE THREAD

**Issue by INFINITE31** [mahtoid/DiscordChatExporterPy#60]
### DiscordChatExporterPy Version

2.2.2

### Discord Version

nextcord 2.2.0

### Bug Description

When I was trying to create a new transcript.

### Bug Traceback

`Traceback (most recent call last):
File "/opt/venv/lib/python3.9/site-packages/chat_exporter/construct/transcript.py", line 74, in export
return await super().build_transcript()
File "/opt/venv/lib/python3.9/site-packages/chat_exporter/construct/transcript.py", line 39, in build_transcript
message_html = await Message(
File "/opt/venv/lib/python3.9/site-packages/chat_exporter/construct/message.py", line 302, in gather
message_html += await MessageConstruct(
File "/opt/venv/lib/python3.9/site-packages/chat_exporter/construct/message.py", line 69, in construct_message
await self.build_message()
File "/opt/venv/lib/python3.9/site-packages/chat_exporter/construct/message.py", line 76, in build_message
await self.build_assets()
File "/opt/venv/lib/python3.9/site-packages/chat_exporter/construct/message.py", line 158, in build_assets
self.embeds += await Embed(e, self.guild).flow()
File "/opt/venv/lib/python3.9/site-packages/chat_exporter/construct/assets/embed.py", line 53, in flow
await self.build_author()
File "/opt/venv/lib/python3.9/site-packages/chat_exporter/construct/assets/embed.py", line 108, in build_author
author_icon = await fill_out(self.guild, embed_author_icon, [
File "/opt/venv/lib/python3.9/site-packages/chat_exporter/ext/html_generator.py", line 38, in fill_out
base = base.replace("{{" + k + "}}", v)
TypeError: replace() argument 2 must be str, not None
Ignoring exception in view <closer timeout=None children=1> for item <Button style=<ButtonStyle.danger: 4> url=None disabled=False label='Close' emoji=None row=None>:
Traceback (most recent call last):
File "/opt/venv/lib/python3.9/site-packages/nextcord/ui/view.py", line 390, in _scheduled_task
await item.callback(interaction)
File "/app/commands/tickets.py", line 70, in cl
transcript = await chat_exporter.export(interaction.channel,limit=None)
File "/opt/venv/lib/python3.9/site-packages/chat_exporter/chat_exporter.py", line 50, in export
return (
AttributeError: 'NoneType' object has no attribute 'html'
`

### Additional Information

I found out that this is becuase nextcord now returns a NoneType object when any embed field is empty instead of Embed.Empty so please consider fixing this issue.

**Comment by mahtoid** [comment]
Hello @INFINITE31 - thank you for letting me know.

I've pushed a change to the `development` branch which will solve for this.

It's quite irritating that their `Embed.Empty` is returning an Object, yet the `Embed` components return `None` directly. If they both returned `None`, then this wouldn't have required a change. Either way, this is solved for now.

---
I'm not entirely sure when I'll push the next version, I'd like to upscale the CSS before releasing. So you may wish to either clone the repo to your project, checkout `development` and adjust file paths - or [view the change I did](https://github.com/mahtoid/DiscordChatExporterPy/commit/1352e9cb37ad0e84b798386ec455fc71ccce234a) and adjust your package files with the same.
