### ISSUE TITLE
'NoneType' object has no attribute 'html' (with matching versions)

### ISSUE THREAD

**Issue by JonasHohenstatter** [mahtoid/DiscordChatExporterPy#63]
### DiscordChatExporterPy Version

2.2 (Latest)

### Discord Version

2.0.1 (Latest)

### Bug Description

This bug keeps happening when I try to create a transcript with my Discord py bot. It worked great for 4 days or so and suddenly this error  pops up. I had it fixed for an hour today, when I restarted the whole Bot after uninstalling chat-exporter and reinstalling it. This is NOT a duplicate of the issue of the top resolved issues, as my Version numbers should match. 

### Bug Traceback

https://pastebin.com/GetfeaBz

16.09 23:25:18 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/construct/transcript.py", line 74, in export
16.09 23:25:18 [Bot] return await super().build_transcript()
16.09 23:25:18 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/construct/transcript.py", line 39, in build_transcript
16.09 23:25:18 [Bot] message_html = await Message(
16.09 23:25:18 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/construct/message.py", line 297, in gather
16.09 23:25:18 [Bot] message_html += await MessageConstruct(
16.09 23:25:18 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/construct/message.py", line 69, in construct_message
16.09 23:25:18 [Bot] await self.build_message()
16.09 23:25:18 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/construct/message.py", line 76, in build_message
16.09 23:25:18 [Bot] await self.build_assets()
16.09 23:25:18 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/construct/message.py", line 167, in build_assets
16.09 23:25:18 [Bot] self.reactions += await Reaction(r, self.guild).flow()
16.09 23:25:18 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/construct/assets/reaction.py", line 13, in flow
16.09 23:25:18 [Bot] await self.build_reaction()
16.09 23:25:18 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/construct/assets/reaction.py", line 25, in build_reaction
16.09 23:25:18 [Bot] await self.create_standard_emoji()
16.09 23:25:18 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/construct/assets/reaction.py", line 37, in create_standard_emoji
16.09 23:25:18 [Bot] react_emoji = await convert_emoji(self.reaction.emoji)
16.09 23:25:18 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/ext/emoji_convert.py", line 88, in convert_emoji
16.09 23:25:18 [Bot] x.append(await convert(ch))
16.09 23:25:18 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/ext/emoji_convert.py", line 74, in convert
16.09 23:25:18 [Bot] shortcode = emoji.demojize(char, use_aliases=True)
16.09 23:25:18 [Bot] AttributeError: module 'emoji' has no attribute 'demojize'
16.09 23:25:18 [Bot] Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy
16.09 23:25:18 [Bot] [2022-09-17 00:25:18] [[ERROR]   ] discord.client: Ignoring exception in on_interaction
16.09 23:25:18 [Bot] Traceback (most recent call last):
16.09 23:25:18 [Bot] File "/.local/lib/python3.9/site-packages/discord/client.py", line 409, in _run_event
16.09 23:25:18 [Bot] await coro(*args, **kwargs)
16.09 23:25:18 [Bot] File "/bot.py", line 251, in on_interaction
16.09 23:25:18 [Bot] transcript = await chat_exporter.export(channel)
16.09 23:25:18 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/chat_exporter.py", line 50, in export
16.09 23:25:18 [Bot] return (
16.09 23:25:18 [Bot] AttributeError: 'NoneType' object has no attribute 'html'

**Comment by JonasHohenstatter** [comment]
The solution was this:

"It seems like you have another library using the emoji namespacing other than emoji"

Please check wheter you have any file that is named emoji.py in the cwd.
