### ISSUE TITLE
AttributeError: 'Message' object has no attribute 'components'

### ISSUE THREAD

**Issue by bombamc** [mahtoid/DiscordChatExporterPy#66]
### DiscordChatExporterPy Version

ver 2.3

### Discord Version

discord.py ver 1.7.9

### Bug Description

Running a command to export chat messages in channel into an html file. When done the bot errors with the following message directing me to this github.

### Bug Traceback

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/chat_exporter/construct/transcript.py", line 123, in export
    return await super().build_transcript()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/chat_exporter/construct/transcript.py", line 46, in build_transcript
    message_html, meta_data = await gather_messages(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/chat_exporter/construct/message.py", line 345, in gather_messages
    content_html, meta_data = await MessageConstruct(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/chat_exporter/construct/message.py", line 77, in construct_message
    await self.build_message()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/chat_exporter/construct/message.py", line 84, in build_message
    await self.build_assets()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/chat_exporter/construct/message.py", line 188, in build_assets
    for c in self.message.components:
AttributeError: 'Message' object has no attribute 'components'
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy

### Additional Information

https://gyazo.com/a94ea6cb82403e047746bb544d984ab6

![a94ea6cb82403e047746bb544d984ab6-png](https://user-images.githubusercontent.com/114297164/192101753-5729688c-b7e7-4d0d-9d55-4fd8c8a0fdeb.jpg)

**Comment by SwordOfSouls** [comment]
Just got the same error

**Comment by SwordOfSouls** [comment]
Solution: With the new discord.py version you need to enable "messages" intent instead of "message_content"

**Comment by mahtoid** [comment]
@bombamc @SwordOfSouls Downgrade to `chat-exporter==1.7.3`. 
You can do this by using: `pip install chat-exporter==1.7.3`

`chat-exporter==2.0` and above is for dpy 2.0  (or fork equivalent) 

#53
