### ISSUE TITLE
Error ChatExporterPy

### ISSUE THREAD

**Issue by GuaxinimDEV** [mahtoid/DiscordChatExporterPy#67]
### DiscordChatExporterPy Version

2.3

### Discord Version

2.0.1

### Bug Description

when I try to do the basic transcript it gives me this error. i'm using slash, so i'm using interaction

### Bug Traceback

Traceback (most recent call last):
  File "C:\Users\adjuto\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\construct\transcript.py", line 123, in export
    return await super().build_transcript()
  File "C:\Users\adjuto\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\construct\transcript.py", line 46, in build_transcript
    message_html, meta_data = await gather_messages(
  File "C:\Users\adjuto\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\construct\message.py", line 345, in gather_messages
    content_html, meta_data = await MessageConstruct(
  File "C:\Users\adjuto\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\construct\message.py", line 77, in construct_message
    await self.build_message()
  File "C:\Users\adjuto\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\construct\message.py", line 84, in build_message
    await self.build_assets()
  File "C:\Users\adjuto\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\construct\message.py", line 183, in build_assets
    self.embeds += await Embed(e, self.guild).flow()
  File "C:\Users\adjuto\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\construct\assets\embed.py", line 53, in flow
    await self.build_author()
  File "C:\Users\adjuto\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\construct\assets\embed.py", line 108, in build_author
    author_icon = await fill_out(self.guild, embed_author_icon, [
  File "C:\Users\adjuto\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\ext\html_generator.py", line 38, in fill_out
    base = base.replace("{{" + k + "}}", v)
TypeError: replace() argument 2 must be str, not _EmptyEmbed
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy

### Additional Information

![image](https://user-images.githubusercontent.com/73598427/192241629-e3bf128e-2f32-43f8-b68e-6203a3d0c540.png)

**Comment by mahtoid** [comment]
I haven't been able to reproduce this issue. Could you run a `pip show` and make sure you only have one instance of an API for Discord loaded. 

By that I mean - you aren't using `discord.py` along with `nextcord` or whatever else. Sometimes that causes conflicts which leads to this issue.

**Comment by GuaxinimDEV** [comment]
![image](https://user-images.githubusercontent.com/73598427/192516267-7ba28f8b-98f8-41b8-8797-01cbc624f018.png)

if I leave this embed in the chat, it gives an error. I only managed to make it work after I removed the embed

i have installed discord.py and nextcord.py

![image](https://user-images.githubusercontent.com/73598427/192517009-7b1e4956-026c-4a84-b360-6d50b7ae6f12.png)

**Comment by mahtoid** [comment]
You should only be using one or the other, not both. That is what causes conflicts which can introduce issues like this. Make sure you are only using **one** framework

**Comment by GuaxinimDEV** [comment]
I'm only using nextcord.py

**Comment by mahtoid** [comment]
Oh? Then this issue should have been solved in `chat-exporter==2.3` 

Make sure you have the latest version of `chat-exporter` and that you have no other Discord frameworks installed. If you still have the issue, then I'll try further to reproduce this issue.

**Comment by GuaxinimDEV** [comment]
nextcord           2.0.0

chat-exporter      2.3

these are the versions that i have installed

**Comment by mahtoid** [comment]
Oh, I think I know the issue. I'll solve this by the end of the week, lacking spare time currently.

If you want to fix this locally, go to [chat_exporter/construct/assets/embed.py](https://github.com/mahtoid/DiscordChatExporterPy/blob/master/chat_exporter/construct/assets/embed.py#L24)  in your venv and remove `and discord.module != "nextcord"`. That should solve your issue. Alternatively, update nextcord to the latest version (2.2).

**Comment by GuaxinimDEV** [comment]
I updated nextcord to 2.2 and also made the indicated modification

![image](https://user-images.githubusercontent.com/73598427/193110816-34191c6d-fd10-4e67-9269-de2660d1ce5a.png)

and when I tried, it gave me this error

![image](https://user-images.githubusercontent.com/73598427/193110465-563adf92-4d60-46ee-8668-35be23c22bde.png)

**Comment by mahtoid** [comment]
Yes, you should have either done one or the other - not both. 

Either:
a) Use the latest version of `nextcord` and uncomment the code.
b) Use the previous version of `nextcord` you was using (2.0) and comment the code.

Not both, both causes the issue in reverse

**Comment by mahtoid** [comment]
@GuaxinimDEV any update?

**Comment by GuaxinimDEV** [comment]
with your help, i managed to make it work, thanks

**Comment by mahtoid** [comment]
Awesome, glad to hear it! 💜 

If you have any other problems, feel free to open up another Issue request on GH or join the Discord. 😄
