### ISSUE TITLE
Errors AttributeError

### ISSUE THREAD

**Issue by Animarlly** [mahtoid/DiscordChatExporterPy#68]
### DiscordChatExporterPy Version

2.3

### Discord Version

discord.py-message-components 2.0a294+gfb291a6

### Bug Description

I have added the example 

```transcript = await chat_exporter.export(ctx.channel)
    
    if transcript is None:
        return

    transcript_file = discord.File(
        io.BytesIO(transcript.encode()),
        filename=f"transcript-{ctx.channel.name}.html",
    )

    message = await ctx.send(file=transcript_file)
    link = await chat_exporter.link(message)

    await ctx.send("Click this link to view the transcript online: " + link)
```

to my code. For the rest it is working fine. The link gets shown in the embed where it belongs but I get all the errors.

When I click on the link, I get also errors. Here is on link of them:

https://mahto.id/chat-exporter?url=https://cdn.discordapp.com/attachments/1025761955941720194/1025762014527766588/transcript-animarlly-ticket.html

### Bug Traceback

Traceback (most recent call last):
  File "C:\Users\cdrma\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\construct\transcript.py", line 123, in export
    return await super().build_transcript()
  File "C:\Users\cdrma\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\construct\transcript.py", line 46, in build_transcript
    message_html, meta_data = await gather_messages(
  File "C:\Users\cdrma\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\construct\message.py", line 345, in gather_messages
    content_html, meta_data = await MessageConstruct(
  File "C:\Users\cdrma\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\construct\message.py", line 77, in construct_message
    await self.build_message()
  File "C:\Users\cdrma\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\construct\message.py", line 84, in build_message
    await self.build_assets()
  File "C:\Users\cdrma\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\construct\message.py", line 189, in build_assets
    self.components += await Component(c, self.guild).flow()
  File "C:\Users\cdrma\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\construct\assets\component.py", line 99, in flow
    for c in self.component.children:
AttributeError: 'ActionRow' object has no attribute 'children'
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy

### Additional Information

![image](https://user-images.githubusercontent.com/102727791/193412173-385666d4-b65c-4d37-9e9b-0b91692e962a.png)

**Comment by mahtoid** [comment]
`discord.py-message-components` is unsupported for `chat-exporter`. 
I don't think there are enough people using this for it to be included in to `chat-exporter` either, I do apologize.

If you do wish to use `chat-exporter` then I suggest either just using `discord.py` or switching to `nextcord`, `disnake` or `py-cord` (these are all supported currently).

**Comment by Animarlly** [comment]
Thank you for the fast response!
