### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'float' - nextcord-2.2.0

### ISSUE THREAD

**Issue by peterlinux11** [mahtoid/DiscordChatExporterPy#70]
### DiscordChatExporterPy Version

2.4

### Discord Version

2.2.0-nextcord

### Bug Description

When i use chat_exporter.export i ll get a error and it just dont create the transcript.
![image](https://user-images.githubusercontent.com/69091177/196034778-699ff1e5-509f-4f76-8513-5b2ecbcb29c1.png)

### Bug Traceback

Traceback (most recent call last):
  File "C:\Users\rigop\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\construct\transcript.py", line 150, in export
    return await super().build_transcript()
  File "C:\Users\rigop\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\construct\transcript.py", line 51, in build_transcript
    message_html, meta_data = await gather_messages(
  File "C:\Users\rigop\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\construct\message.py", line 353, in gather_messages
    content_html, meta_data = await MessageConstruct(
  File "C:\Users\rigop\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\construct\message.py", line 77, in construct_message
    await self.build_message()
  File "C:\Users\rigop\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\construct\message.py", line 84, in build_message
    await self.build_assets()
  File "C:\Users\rigop\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\construct\message.py", line 191, in build_assets
    self.embeds += await Embed(e, self.guild).flow()
  File "C:\Users\rigop\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\construct\assets\embed.py", line 48, in flow
    self.check_against = _gather_checker()
  File "C:\Users\rigop\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_exporter\construct\assets\embed.py", line 24, in _gather_checker
    if hasattr(discord.Embed, "Empty") and (discord.module != "nextcord" or discord.__version__ < 2.2):
TypeError: '<' not supported between instances of 'str' and 'float'
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy

### Additional Information

![image](https://user-images.githubusercontent.com/69091177/196034641-418d2e22-3fd8-45c0-ac01-61cf6020c354.png)

**Comment by mahtoid** [comment]
Hello @peterlinux11 - thank you for the report.

Someone reported this within the Discord too and I'm just awaiting them to get back to me to confirm a fix worked. Will leave this open until I push a hotfix.

**Comment by mahtoid** [comment]
Pushed the solution, I just removed the version check. 👀 
If you run `pip install --upgrade chat-exporter` you will be up and running once again. 

If you notice any other issues, feel free to raise another Github Issue or alternatively join the Discord. Have a great day 💜
