### ISSUE TITLE
AttribueError: type object 'MessageType' has no attribute 'thread_created'

### ISSUE THREAD

**Issue by Joniii11** [mahtoid/DiscordChatExporterPy#76]
### DiscordChatExporterPy Version

Version: 2.5.0

### Discord Version

Discord.py v1.7.3

### Bug Description

I tried to use the quick_export function
`await chat_exporter.quick_export(ctx.channel)`

### Bug Traceback

Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\chat_exporter\construct\transcript.py", line 164, in export
    return await super().build_transcript()
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\chat_exporter\construct\transcript.py", line 55, in build_transcript
    message_html, meta_data = await gather_messages(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\chat_exporter\construct\message.py", line 389, in gather_messages
    content_html, meta_data = await MessageConstruct(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\chat_exporter\construct\message.py", line 80, in construct_message
    elif discord.MessageType.thread_created == self.message.type:
AttributeError: type object 'MessageType' has no attribute 'thread_created'
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy

**Comment by mahtoid** [comment]
Hey @Joniii11 

If you're using `discord.py==1.7.3` then you will have to use `chat-exporter==1.7.3`. If you choose to do this, then you'll also need to downgrade the `emoji` package to `1.7.0` to avoid the `use_aliases` error.

It may be better if you upgrade your `discord.py` instead. 

Let me know if these help.

**Comment by Joniii11** [comment]
Hello  @mahtoid

I thought already to upgrade `discord.py` but i don't understand it how everything functions then. And i am not the best at coding you know. And really no one could help me to migrate to v2 so yeah.

I will implement now the code and downgrade everything.

**Comment by mahtoid** [comment]
Most of the basic usage is still the same, it's mostly implementation for Slash commands if I remember correctly (along with using the latest Discord API). A lot of information you'll require will be within the Discord.py API documentation, which is pretty handy and easy to understand.

I'm assuming that this issue is solved for you, so closing out the issue. Feel free to re-open if you have the same issue.
