### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by Ceeq9717** [mahtoid/DiscordChatExporterPy#85]
### DiscordChatExporterPy Version

2.5.3

### Discord Version

pycord 2.4.1.dev109+g7f192feb

### Bug Description

When I wanted to export the chat of a channel I got an error which is in the title. 

### Bug Traceback

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/chat_exporter/construct/transcript.py", line 166, in export
    return await super().build_transcript()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/chat_exporter/construct/transcript.py", line 55, in build_transcript
    message_html, meta_data = await gather_messages(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/chat_exporter/construct/message.py", line 389, in gather_messages
    content_html, meta_data = await MessageConstruct(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/chat_exporter/construct/message.py", line 83, in construct_message
    await self.build_message()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/chat_exporter/construct/message.py", line 91, in build_message
    await self.build_assets()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/chat_exporter/construct/message.py", line 226, in build_assets
    self.embeds += await Embed(e, self.guild).flow()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/chat_exporter/construct/assets/embed.py", line 57, in flow
    await self.build_author()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/chat_exporter/construct/assets/embed.py", line 109, in build_author
    self.author = html.escape(self.embed.author.name) if self.embed.author.name != self.check_against else ""
AttributeError: 'NoneType' object has no attribute 'name'
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy

### Additional Information

![Traceback Screenshot](https://github.com/mahtoid/DiscordChatExporterPy/assets/114670723/f55038e2-1ad5-44e6-96c8-4936dd6e2fe4)

**Comment by mahtoid** [comment]
This has been solved on the `2.6.0` branch of `chat-exporter`, which you can clone and use for now. Once the release is finished I will push this version out.
