### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by maeHD666** [mahtoid/DiscordChatExporterPy#90]
### DiscordChatExporterPy Version

2.6.1

### Discord Version

pycord=2.4

### Bug Description

TypeError: EmbedAuthor.__init__() missing 1 required positional argument: 'name'
![image](https://github.com/mahtoid/DiscordChatExporterPy/assets/86745091/fba1cf06-ef38-4c9e-bd9f-807025db8f42)

### Bug Traceback

Traceback (most recent call last):
  File "C:\Users\marce\AppData\Local\Programs\Python\Python311\Lib\site-packages\chat_exporter\construct\transcript.py", line 171, in export
    return await super().build_transcript()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marce\AppData\Local\Programs\Python\Python311\Lib\site-packages\chat_exporter\construct\transcript.py", line 56, in build_transcript
    message_html, meta_data = await gather_messages(
                              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marce\AppData\Local\Programs\Python\Python311\Lib\site-packages\chat_exporter\construct\message.py", line 455, in gather_messages
    content_html, meta_data = await MessageConstruct(
                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marce\AppData\Local\Programs\Python\Python311\Lib\site-packages\chat_exporter\construct\message.py", line 92, in construct_message
    await self.build_message()
  File "C:\Users\marce\AppData\Local\Programs\Python\Python311\Lib\site-packages\chat_exporter\construct\message.py", line 100, in build_message
    await self.build_assets()
  File "C:\Users\marce\AppData\Local\Programs\Python\Python311\Lib\site-packages\chat_exporter\construct\message.py", line 246, in build_assets
    self.embeds += await Embed(e, self.guild).flow()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marce\AppData\Local\Programs\Python\Python311\Lib\site-packages\chat_exporter\construct\assets\embed.py", line 57, in flow
    await self.build_author()
  File "C:\Users\marce\AppData\Local\Programs\Python\Python311\Lib\site-packages\chat_exporter\construct\assets\embed.py", line 110, in build_author
    self.embed.author and self.embed.author.name != self.check_against
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\marce\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\embeds.py", line 704, in author
    return EmbedAuthor(**getattr(self, "_author", {}))  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: EmbedAuthor.__init__() missing 1 required positional argument: 'name'

**Comment by maeHD666** [comment]
Ich konnte den Bug "fixxen". In dem Chat war ein Embed welchen keinen Author hatte. Und da war der Chat-Exporter wohl überfragt

**Comment by mahtoid** [comment]
This is a Pycord issue, they did originally solve this in their development branch. Could you double check that you have the latest?

**Comment by mahtoid** [comment]
Closing due to inactivity
