### ISSUE TITLE
A Error

### ISSUE THREAD

**Issue by xiaozhe0000** [mahtoid/DiscordChatExporterPy#93]
### DiscordChatExporterPy Version

2.6.1

### Discord Version

2.3.2

### Bug Description
code :
```
import discord
import chat_exporter
from discord.ext import commands



bot = commands.Bot(command_prefix="!", intents=discord.Intents.all())


@bot.command()
async def save(ctx: commands.Context):
    await chat_exporter.quick_export(ctx.channel)

bot.run("")
```

### Bug Traceback

```Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\chat_exporter\construct\transcript.py", line 171, in export
    return await super().build_transcript()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\chat_exporter\construct\transcript.py", line 56, in build_transcript
    message_html, meta_data = await gather_messages(
                              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\chat_exporter\construct\message.py", line 455, in gather_messages
    content_html, meta_data = await MessageConstruct(
                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\chat_exporter\construct\message.py", line 92, in construct_message
    await self.build_message()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\chat_exporter\construct\message.py", line 96, in build_message
    await self.build_content()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\chat_exporter\construct\message.py", line 152, in build_content
    self.message.content = await fill_out(self.guild, message_content, [
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\chat_exporter\ext\html_generator.py", line 28, in fill_out
    v = await ParseMarkdown(v).standard_message_flow()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\chat_exporter\parse\markdown.py", line 11, in standard_message_flow
    self.https_http_links()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\chat_exporter\parse\markdown.py", line 373, in https_http_links
    match_url = re.search(pattern, word).group(1)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy```

### Additional Information

_No response_

**Comment by mahtoid** [comment]
Hello @shizhhe - I have this noted down already to be solved in the next version. I will keep this issue alive until it is at least in a development branch. This is due to a link containing some other character, such as `)` at the end of it.

**Comment by shizhhe** [comment]
> Hello @shizhhe - I have this noted down already to be solved in the next version. I will keep this issue alive until it is at least in a development branch. This is due to a link containing some other character, such as `)` at the end of it.

Thanks!

**Comment by CT-34589** [comment]
is 2.7.0 released on pypi yet or is it still using 2.6.1?

**Comment by mahtoid** [comment]
@CT-34589 Still 2.6.1, terribly sorry! 🙃

**Comment by mahtoid** [comment]
@CT-34589 as per the other issue, the latest version has now been pushed. 

`pip install --upgrade chat-exporter`
cc: @xiaozhe0000
