### ISSUE TITLE
export() blocks

### ISSUE THREAD

**Issue by MeHaVr** [mahtoid/DiscordChatExporterPy#97]
### DiscordChatExporterPy Version

2.6.1

### Discord Version

pycord 2.4.1

### Bug Description

Calling export() blocks and later returns with a timeout error:

```
@discord.ui.button(label="Delete Ticket 🎫", style = discord.ButtonStyle.red, custom_id="delete")
    async def delete_button(self, button: discord.ui.Button, interaction: discord.Interaction):
# ...
     transcript = await chat_exporter.export( interaction.channel )
#...
```

### Bug Traceback

Traceback (most recent call last):
  File "/Users/alex/Library/Python/3.9/lib/python/site-packages/chat_exporter/construct/transcript.py", line 171, in export
    return await super().build_transcript()
  File "/Users/alex/Library/Python/3.9/lib/python/site-packages/chat_exporter/construct/transcript.py", line 56, in build_transcript
    message_html, meta_data = await gather_messages(
  File "/Users/alex/Library/Python/3.9/lib/python/site-packages/chat_exporter/construct/message.py", line 455, in gather_messages
    content_html, meta_data = await MessageConstruct(
  File "/Users/alex/Library/Python/3.9/lib/python/site-packages/chat_exporter/construct/message.py", line 92, in construct_message
    await self.build_message()
  File "/Users/alex/Library/Python/3.9/lib/python/site-packages/chat_exporter/construct/message.py", line 100, in build_message
    await self.build_assets()
  File "/Users/alex/Library/Python/3.9/lib/python/site-packages/chat_exporter/construct/message.py", line 252, in build_assets
    self.components += await Component(c, self.guild).flow()
  File "/Users/alex/Library/Python/3.9/lib/python/site-packages/chat_exporter/construct/assets/component.py", line 100, in flow
    await self.build_component(c)
  File "/Users/alex/Library/Python/3.9/lib/python/site-packages/chat_exporter/construct/assets/component.py", line 41, in build_component
    await self.build_button(c)
  File "/Users/alex/Library/Python/3.9/lib/python/site-packages/chat_exporter/construct/assets/component.py", line 53, in build_button
    self.buttons += await fill_out(self.guild, component_button, [
  File "/Users/alex/Library/Python/3.9/lib/python/site-packages/chat_exporter/ext/html_generator.py", line 28, in fill_out
    v = await ParseMarkdown(v).standard_message_flow()
  File "/Users/alex/Library/Python/3.9/lib/python/site-packages/chat_exporter/parse/markdown.py", line 14, in standard_message_flow
    await self.parse_emoji()
  File "/Users/alex/Library/Python/3.9/lib/python/site-packages/chat_exporter/parse/markdown.py", line 62, in parse_emoji
    self.content = await convert_emoji([word for word in self.content])
  File "/Users/alex/Library/Python/3.9/lib/python/site-packages/chat_exporter/ext/emoji_convert.py", line 88, in convert_emoji
    x.append(await convert(ch))
  File "/Users/alex/Library/Python/3.9/lib/python/site-packages/chat_exporter/ext/emoji_convert.py", line 79, in convert
    if await valid_src(src):
  File "/Users/alex/Library/Python/3.9/lib/python/site-packages/chat_exporter/ext/cache.py", line 8, in func
    value = await coro
  File "/Users/alex/Library/Python/3.9/lib/python/site-packages/chat_exporter/ext/emoji_convert.py", line 47, in valid_src
    async with session.get(src) as resp:
  File "/Users/alex/Library/Python/3.9/lib/python/site-packages/aiohttp/client.py", line 1167, in __aenter__
    self._resp = await self._coro
  File "/Users/alex/Library/Python/3.9/lib/python/site-packages/aiohttp/client.py", line 663, in _request
    break
  File "/Users/alex/Library/Python/3.9/lib/python/site-packages/aiohttp/helpers.py", line 725, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy

**Comment by mahtoid** [comment]
@MeHaVr terrible sorry for missing this. 

Are you still receiving the issue, and is it on every channel (with an emoji)? This shouldn't be an issue in `2.6.1`, this seems quite similar to when the former Twemoji CDN died - however the new Twemoji CDN we switched over too should be good.

**Comment by MeHaVr** [comment]
Thx its working fine :)
