### ISSUE TITLE
erroring in some channels but not others

### ISSUE THREAD

**Issue by CT-34589** [mahtoid/DiscordChatExporterPy#98]
### DiscordChatExporterPy Version

2.6.1

### Discord Version

py-cord 2.4.1

### Bug Description

simple transcript 
```py

from Bot.DatacoreBot import DatacoreBot

import io
import discord
import chat_exporter
from discord.ext import commands


open_transcripts = 0

class CExport(commands.Cog):
    def __init__(self, bot: DatacoreBot):
        self.bot = bot

    @commands.command()
    async def ctranscript(self, ctx: commands.Context):
        await ctx.message.delete()

        global open_transcripts
        open_transcripts += 1

        print('start |', ctx.guild.name, '|', ctx.channel.name, "open tasks |", open_transcripts)
        transcript = await chat_exporter.export(
            channel=ctx.channel,
            limit=None,
            tz_info="UTC",
            military_time=True,
            bot=self.bot
        )

        if transcript is None:
            return

        transcript_file = discord.File(
            io.BytesIO(transcript.encode()),
            filename=f"transcript-{ctx.channel.name}.html",
        )
        print('end |', ctx.guild.name, '|', ctx.channel.name)
        open_transcripts -= 1
        await ctx.author.send(file=transcript_file)

def setup(bot: DatacoreBot):
    bot.add_cog(CExport(bot))
```

### Bug Traceback

```
Traceback (most recent call last):
05.02 12:38:58 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/construct/transcript.py", line 171, in export
05.02 12:38:58 [Bot] return await super().build_transcript()
05.02 12:38:58 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/construct/transcript.py", line 56, in build_transcript
05.02 12:38:58 [Bot] message_html, meta_data = await gather_messages(
05.02 12:38:58 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/construct/message.py", line 455, in gather_messages
05.02 12:38:58 [Bot] content_html, meta_data = await MessageConstruct(
05.02 12:38:58 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/construct/message.py", line 84, in construct_message
05.02 12:38:58 [Bot] await self.build_pin()
05.02 12:38:58 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/construct/message.py", line 106, in build_pin
05.02 12:38:58 [Bot] await self.build_pin_template()
05.02 12:38:58 [Bot] File "/.local/lib/python3.9/site-packages/chat_exporter/construct/message.py", line 339, in build_pin_template
05.02 12:38:58 [Bot] ("REF_MESSAGE_ID", str(self.message.reference.message_id), PARSE_MODE_NONE)
05.02 12:38:58 [Bot] AttributeError: 'NoneType' object has no attribute 'message_id'
```

**Comment by doluk** [comment]
Hey there, sorry for the slow response. I fixed that as a part of my pr in #96

**Comment by CT-34589** [comment]
Will there be a new release with the bug fixes

**Comment by mahtoid** [comment]
@CT-34589 Sorry for the delay, the latest version has now been pushed. 

`pip install --upgrade chat-exporter`
